version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Update Nodejs
          command: "sudo apt install nodejs"
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - run:
          name: Install Yarn
          command: "sudo npm install --global yarn"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate Builds
          command: yarn build

      - store_artifacts:
          path: ~/repo/out/make